server:
  port: 3001  #????
  servlet:
    context-path: /  #?? ??? /blog? ????  ex)http://localhost:8000/blog
    encoding:
      charset: UTF-8  #UTF-8? ?????????   ???????
      enabled: true # true? ???? ?????  ???????
      force: true  #??? ?? ????? ??? ???? ????  ???????
  tomcat:
    max-http-form-post-size: 10485760

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/  #? ???? ??? ?? ?????? /WEB-INF/views/? ????
      suffix: .jsp  #? ?? ?? ?? ???? .jsp? ????

  jackson:
    serialization:
      fail-on-empty-beans: false
